SLIDE_SOURCES := $(wildcard Course*/slides*.md)
SLIDE_TARGETS := $(SLIDE_SOURCES:.md=.pptx)

# Course01: one figure per concept, all generated by scripts/make_figures_c01.py
# the course logistics, then estimation theory, then the supervised
# and unsupervised halves of the reminder
C01_STEMS := about prerequisites applications estimation_setup bias variance \
             dartboard eq_mse three_methods mom_idea mom_gaussian mom_props \
             eq_likelihood likelihood_build log_likelihood mle_idea mle_gaussian \
             mle_props bayes_setup eq_posterior cost_idea cost_zoo prior_effect \
             divisor_family mle_variance bessel mse_divisor estimators_compare \
             supervised_principle regression_vs_classification supervised_apps \
             discriminative_vs_generative eq_bayes_classifier bayes_ingredients \
             eq_naive_bayes spam_filter laplace_smoothing naive_bayes_gaussian \
             lda_setup lda_fit_steps lda_why_linear qda_shapes lda_qda_cost \
             lda_derivation lda_boundary lda_training qda_vs_lda unsupervised_principle \
             dimred_vs_clustering unsupervised_apps eq_kmeans kmeans_algorithm \
             kmeans_weaknesses pca_projection pca_spectrum concept_map

C01_FIGURES := $(foreach f,$(C01_STEMS),Course01/img/$(f).png)

.PHONY: slides figures clean-slides clean-figures
slides: $(SLIDE_TARGETS)

figures: $(C01_FIGURES)

$(C01_FIGURES): scripts/make_figures_c01.py
	python3 scripts/make_figures_c01.py Course01/img

Course01/slides.pptx: $(C01_FIGURES)

%.pptx: %.md scripts/fit_pptx.py
	pandoc $< -o $@ --slide-level=2 --resource-path=$(dir $<)
	python3 scripts/fit_pptx.py $@

clean-slides:
	rm -f $(SLIDE_TARGETS)

clean-figures:
	rm -f $(C01_FIGURES)
