SLIDE_SOURCES := $(wildcard Course*/slides*.md)
SLIDE_TARGETS := $(SLIDE_SOURCES:.md=.pptx)

# Course01: one figure per concept, all generated by scripts/make_figures_c01.py
# the course logistics, then estimation theory, then the supervised
# and unsupervised halves of the reminder
C01_STEMS := about prerequisites applications estimation_setup bias variance \
             dartboard eq_mse three_methods mom_idea mom_gaussian mom_props \
             eq_likelihood likelihood_build log_likelihood mle_idea mle_gaussian \
             mle_props bayes_setup eq_posterior cost_idea cost_zoo prior_effect \
             divisor_family mle_variance bessel mse_divisor estimators_compare \
             supervised_principle regression_vs_classification supervised_apps \
             discriminative_vs_generative eq_bayes_classifier bayes_ingredients \
             eq_naive_bayes spam_filter laplace_smoothing naive_bayes_gaussian \
             lda_setup lda_fit_steps lda_why_linear qda_shapes lda_qda_cost \
             lda_derivation lda_boundary lda_training qda_vs_lda unsupervised_principle \
             dimred_vs_clustering unsupervised_apps eq_kmeans kmeans_algorithm \
             kmeans_weaknesses pca_projection pca_spectrum concept_map

C01_FIGURES := $(foreach f,$(C01_STEMS),Course01/img/$(f).png)

# Course01 also presents the suggested project datasets, one slide each,
# drawn from the real data by scripts/make_figures_datasets.py
# (downloads into .cache/datasets/ on the first build)
DS_STEMS := ds_stars ds_ames ds_dvf ds_breast_cancer ds_adult ds_creditcard ds_spambase \
            ds_earthquakes ds_velib ds_online_retail ds_wholesale ds_newsgroups \
            ds_olivetti ds_movielens ds_galaxies ds_penguins ds_bsds ds_fashion_mnist \
            ds_pbmc ds_har ds_coil20

DS_FIGURES := $(foreach f,$(DS_STEMS),Course01/img/$(f).png)

# Course02: one figure per concept, all generated by scripts/make_figures_c02.py
# the linear-regression reminders, then the penalties, then M-estimation
# and the IRLS loop
C02_STEMS := regression_setting regression_apps why_linear eq_linear_model ls_residuals \
             eq_normal_equations hat_matrix collinear_example collinear_valley \
             near_collinear ls_variance high_dim eq_regularized penalty_zoo \
             penalty_geometry lambda_path thresholding prox_idea eq_prox outlier_demo \
             squared_loss_pull outliers_vs_mismodelling eq_m_estimation rho_from_density \
             eq_robust_regression rho_zoo eq_stationarity eq_weight psi_and_weights \
             influence_demo weights_on_data eq_irls irls_loop irls_steps irls_algorithm \
             mm_idea eq_mm delta_meaning delta_scale tuning_delta robust_map \
             logistic_setting eq_logodds sigmoid eq_softmax logistic_loss why_not_least_squares \
             eq_logistic_irls logistic_mm logistic_fit logistic_props

C02_FIGURES := $(foreach f,$(C02_STEMS),Course02/img/$(f).png)

.PHONY: slides figures clean-slides clean-figures
slides: $(SLIDE_TARGETS)

figures: $(C01_FIGURES) $(DS_FIGURES) $(C02_FIGURES)

$(C01_FIGURES): scripts/make_figures_c01.py
	python3 scripts/make_figures_c01.py Course01/img

$(DS_FIGURES): scripts/make_figures_datasets.py scripts/make_figures_c01.py
	python3 scripts/make_figures_datasets.py Course01/img

$(C02_FIGURES): scripts/make_figures_c02.py
	python3 scripts/make_figures_c02.py Course02/img

Course01/slides.pptx: $(C01_FIGURES) $(DS_FIGURES)
Course02/slides.pptx: $(C02_FIGURES)

%.pptx: %.md scripts/fit_pptx.py
	pandoc $< -o $@ --slide-level=2 --resource-path=$(dir $<)
	python3 scripts/fit_pptx.py $@

clean-slides:
	rm -f $(SLIDE_TARGETS)

clean-figures:
	rm -f $(C01_FIGURES) $(DS_FIGURES) $(C02_FIGURES)
