SLIDE_SOURCES := $(wildcard Course*/slides*.md)
SLIDE_TARGETS := $(SLIDE_SOURCES:.md=.pptx)

# Course01: one figure per concept, all generated by scripts/make_figures_c01.py
# the course logistics, then estimation theory, then the supervised
# and unsupervised halves of the reminder
C01_STEMS := about prerequisites applications estimation_setup bias variance \
             dartboard eq_mse three_methods mom_idea mom_gaussian mom_props \
             eq_likelihood likelihood_build log_likelihood mle_idea mle_gaussian \
             mle_props bayes_setup eq_posterior cost_idea cost_zoo prior_effect \
             divisor_family mle_variance bessel mse_divisor estimators_compare \
             supervised_principle regression_vs_classification supervised_apps \
             discriminative_vs_generative eq_bayes_classifier bayes_ingredients \
             eq_naive_bayes spam_filter laplace_smoothing naive_bayes_gaussian \
             lda_setup lda_fit_steps lda_why_linear qda_shapes lda_qda_cost \
             lda_derivation lda_boundary lda_training qda_vs_lda unsupervised_principle \
             dimred_vs_clustering unsupervised_apps eq_kmeans kmeans_algorithm \
             kmeans_weaknesses pca_projection pca_spectrum concept_map

C01_FIGURES := $(foreach f,$(C01_STEMS),Course01/img/$(f).png)

# Course01 also presents the suggested project datasets, one slide each,
# drawn from the real data by scripts/make_figures_datasets.py
# (downloads into .cache/datasets/ on the first build)
DS_STEMS := ds_stars ds_ames ds_dvf ds_breast_cancer ds_adult ds_creditcard ds_spambase \
            ds_earthquakes ds_velib ds_online_retail ds_wholesale ds_newsgroups \
            ds_olivetti ds_movielens ds_galaxies ds_penguins ds_bsds ds_fashion_mnist \
            ds_pbmc ds_har ds_coil20

DS_FIGURES := $(foreach f,$(DS_STEMS),Course01/img/$(f).png)

# Course02: one figure per concept, all generated by scripts/make_figures_c02.py
# the linear-regression reminders, then the penalties, then M-estimation
# and the IRLS loop
C02_STEMS := regression_setting regression_apps why_linear linreg_multi linreg_basis \
             eq_linear_model ls_residuals \
             eq_normal_equations hat_matrix collinear_example collinear_valley \
             near_collinear ls_variance high_dim eq_regularized penalty_zoo \
             penalty_geometry lambda_path thresholding prox_idea eq_prox outlier_demo \
             squared_loss_pull outliers_vs_mismodelling eq_m_estimation rho_from_density \
             eq_robust_regression rho_zoo eq_stationarity eq_weight psi_and_weights \
             influence_demo weights_on_data eq_irls irls_loop irls_steps irls_algorithm \
             mm_idea eq_mm delta_meaning delta_scale tuning_delta robust_map \
             logistic_setting eq_logodds sigmoid eq_softmax logistic_loss why_not_least_squares \
             eq_logistic_irls logistic_mm logistic_fit logistic_props

C02_FIGURES := $(foreach f,$(C02_STEMS),Course02/img/$(f).png)

# Course03: one figure per concept, all generated by scripts/make_figures_c03.py
# the hard margin and its dual, then slack, then kernels, then the
# multiclass wrappers
C03_STEMS := svm_setting svm_which svm_margin eq_margin canonical eq_primal \
             eq_squared_slack slack_or_max eq_dual duality_saddle kkt_recover \
             support_vectors not_separable slack_idea eq_soft svm_c eq_svm hinge_loss \
             svm_kernel xor_example eq_kernel_trick svm_similarity eq_kernel_conditions \
             svm_kernel_zoo svm_kernels kernel_cv feature_scaling svr svr_dual \
             svr_epsilon svm_cost eq_kernel_dual kernel_props multiclass svm_map

C03_FIGURES := $(foreach f,$(C03_STEMS),Course03/img/$(f).png)

# Course03-bis: trees and forests ported from Course03/imports/figs.py,
# the boosting family imported from Course03/imports/figs2.py, both by
# scripts/make_figures_c03bis.py
C03BIS_STEMS := additive_model bagging_vs_boosting boosting_overfit boosting_stages \
                cat_chain cat_example cat_leak_why cat_oblivious cat_ordered_ts \
                eq_boosting eq_forest_variance eq_leaf_objective eq_xgboost \
                forest_boundary forest_correlation forest_diagram forest_features \
                forest_idea forest_ntrees forest_variance gbm_compare impurity \
                learning_rate lgbm_binned_scan lgbm_bins lgbm_goss lgbm_leafwise \
                lgbm_prefix lgbm_subtract max_features shrinkage tree_grow \
                tree_instability tree_overfit tree_questions tree_regression \
                tree_split xgb_gh xgb_leaf_predict xgb_leaf_score xgb_split_search \
                zoo

C03BIS_FIGURES := $(foreach f,$(C03BIS_STEMS),Course03/img-bis/$(f).png)

# Course04: clustering — k-means, hierarchical, DBSCAN and HDBSCAN,
# all generated by scripts/make_figures_c04.py
C04_STEMS := agglomerative_steps algo_compare cluster_distinctions cluster_types \
             clustering_apps clustering_map clustering_setting clustering_vs_dimred \
             complete_vs_partial condense_example condensed_tree core_distance \
             dbscan_algorithm dbscan_epsilon dbscan_idea dbscan_knn_elbow \
             dbscan_minpts dbscan_points dbscan_props dbscan_vs_kmeans dendrogram_cut \
             distance_zoo eq_dissimilarity eq_huygens eq_inertia eq_kmeans \
             eq_mountain eq_mutual_reachability eq_ward eq_ward_proof \
             exclusive_vs_overlapping extract_example good_clustering \
             hamming_distance hard_vs_fuzzy hdbscan_hierarchy hdbscan_idea \
             hdbscan_props hdbscan_result hdbscan_steps hierarchical_props \
             hierarchy_idea homogeneous_vs_heterogeneous inertia_defined \
             kmeans_algorithm kmeans_alternatives kmeans_init kmeans_limits \
             linkage_compare linkage_definitions linkage_dendrograms linkage_props \
             linkage_update mountain_idea mountain_props mountain_steps mreach_effect \
             mreach_example mreach_intuition mst_build mst_step mst_to_hierarchy \
             partitional_vs_hierarchical stability_example stability_idea \
             subtractive_clustering ward_idea wpgma wpgma_vs_upgma

C04_FIGURES := $(foreach f,$(C04_STEMS),Course04/img/$(f).png)


.PHONY: slides figures clean-slides clean-figures
slides: $(SLIDE_TARGETS)

figures: $(C01_FIGURES) $(DS_FIGURES) $(C02_FIGURES) $(C03_FIGURES) \
         $(C03BIS_FIGURES) $(C04_FIGURES)

$(C01_FIGURES): scripts/make_figures_c01.py
	python3 scripts/make_figures_c01.py Course01/img

$(DS_FIGURES): scripts/make_figures_datasets.py scripts/make_figures_c01.py
	python3 scripts/make_figures_datasets.py Course01/img

$(C02_FIGURES): scripts/make_figures_c02.py
	python3 scripts/make_figures_c02.py Course02/img

$(C03_FIGURES): scripts/make_figures_c03.py
	python3 scripts/make_figures_c03.py Course03/img

$(C03BIS_FIGURES): scripts/make_figures_c03bis.py Course03/imports/figs2.py
	python3 scripts/make_figures_c03bis.py Course03/img-bis

$(C04_FIGURES): scripts/make_figures_c04.py
	python3 scripts/make_figures_c04.py Course04/img


Course01/slides.pptx: $(C01_FIGURES) $(DS_FIGURES)
Course02/slides.pptx: $(C02_FIGURES)
Course03/slides.pptx: $(C03_FIGURES)
Course03/slides-bis.pptx: $(C03BIS_FIGURES)
Course04/slides.pptx: $(C04_FIGURES)

%.pptx: %.md scripts/fit_pptx.py
	pandoc $< -o $@ --slide-level=2 --resource-path=$(dir $<)
	python3 scripts/fit_pptx.py $@

clean-slides:
	rm -f $(SLIDE_TARGETS)

clean-figures:
	rm -f $(C01_FIGURES) $(DS_FIGURES) $(C02_FIGURES) $(C03_FIGURES) \
	        $(C03BIS_FIGURES) $(C04_FIGURES)
